[theme]

base = "dark"
# Primary accent for interactive elements
primaryColor = "orange"

backgroundColor = "#00172B"
secondaryBackgroundColor = "#012442"

# Background color for the main content area
# Background color for sidebar and most interactive widgets
# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
